name: Build and cache with Nix

on:
  push:        # runs on every commit to any branch
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Use Cachix
        uses: cachix/cachix-action@v12
        with:
          name: charon
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build flake
        run: nix build

      - name: Upload build logs if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: /tmp/nix-build-*
